import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

if __name__ == "__main__":
    m = 1.0  # mass of end effector [kg]
    r = 1.0  # length of link [m]
    g = 9.80665  # gravitation acceleration [m/s^2]
    I = (
        m * r ** 2
    )  # moment of inertia of point mass at the end of massless link [kg*m^3]
    q_0 = 0.0  # angle at t=0.0 [rad]
    qd_0 = 0.0  # velocity at t=0.0 [rad/s]
    Δt = 0.001  # step size
    t_eval = np.arange(
        0.0, 1.0, Δt
    )  # time instants for which to evaluate the solution y(t)

    # torque generated by motor
    def τ_motor(t):
        return 0.0

    # torque generated by gravity
    def τ_g(q):
        return -m * g * r * np.cos(q)

    def dydt(t, y):
        q, qd = y
        qdd = (τ_motor(t) + τ_g(q)) / I
        return np.array((qd, qdd))

    # obtain solution to ordinary differential equations using forward Euler integration scheme
    y0 = (q_0, qd_0)
    y = [y0]
    y_cur = y0

    for t in t_eval[1:]:
        y_cur = y_cur + Δt * dydt(t, y_cur)
        y.append(y_cur)

    y = np.array(y)

    # plotting
    fig, ax = plt.subplots()
    ax.plot(t_eval, y[:, 0], label="angle")
    ax.plot(t_eval, y[:, 1], label="velocity")
    ax.legend()
    ax.set_xlabel("t")
    plt.show()

    # animation
    fig, ax = plt.subplots()
    ax.set_xlim(-2, 2)
    ax.set_ylim(-2, 2)
    ax.set_aspect("equal")
    ax.set_xlabel("x")
    ax.set_ylabel("y")

    (line,) = ax.plot([], [], "o-", lw=2)
    time_template = "time = %.1fs"
    time_text = ax.text(0.05, 0.9, "", transform=ax.transAxes)

    def update(i):
        angle, vel = y[i]
        xx = np.cos(angle) * r
        yy = np.sin(angle) * r
        line.set_data([0.0, xx], [0.0, yy])
        time_text.set_text(time_template % (i * Δt))
        return (line, time_text)

    ani = FuncAnimation(fig, update, frames=range(y.shape[0]), blit=True, interval=Δt)
    plt.show()
